server:
  port: 8080

logging:
  level:
    root: INFO
    com.labcomu: DEBUG
  file: 
    name: "/logs/application-debug.log"
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  